In [5]:
# tema 1

import numpy as np

# Crear un arreglo inicial con elementos iguales a 1
arreglo_inicial = np.ones((3, 3), dtype=int)

# Obtener las dimensiones del arreglo inicial
filas, columnas = arreglo_inicial.shape

# Crear un nuevo arreglo con un marco de ceros
arreglo_con_marco = np.zeros((filas + 2, columnas + 2), dtype=int)

# Copiar el arreglo inicial en el centro del arreglo con marco
arreglo_con_marco[1:-1, 1:-1] = arreglo_inicial

# Imprimir el arreglo con marco
print(arreglo_con_marco)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [6]:
# tema 2
import numpy as np

arreglo = np.arange(1, 101)  # Crear el arreglo de 1 a 100

# Encontrar los elementos que son múltiplos de 2 y 3
multiplos_2_y_3 = arreglo[(arreglo % 2 == 0) & (arreglo % 3 == 0)]

# Calcular la suma de los elementos encontrados
suma_elementos = np.sum(multiplos_2_y_3)

print("Elementos múltiplos de 2 y 3:", multiplos_2_y_3)
print("Suma de los elementos encontrados:", suma_elementos)

Elementos múltiplos de 2 y 3: [ 6 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96]
Suma de los elementos encontrados: 816
